# Site settings
theme: jekyll-dash

title: Laggy's Blog
description: >-
  A blog for CTF writeups, gists and random stuff I made on the Internet.
url: "https://alaggydev.github.io"
baseurl: ""
timezone: Asia/Hong_Kong
lang: en

author:
  name: Laggy
  github: ALaggyDev

github:
  username: ALaggyDev

# Google Analytics
analytics:
  google:
    id: G-F7F18F41ED
google_analytics: G-F7F18F41ED

# Site Verification Settings
webmaster_verifications:
  google: xru9EFczozR4VYCba2k39a7A71pwQSVP4D70JN9oKE0

# jekyll-paginate
paginate: 10
paginate_path: "/blog/page:num/"

# jekyll-tagging
tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

plugins:
  - jekyll-paginate
  - jekyll/tagging

dash:
  date_format: "%b %-d, %Y"
  animation_speed: 50
  rtl: false
  avatar_source: local
  avatar_path: /assets/img/main_page/keyboard-icon.jpg
  show_author: true
  social_links:
    - url: https://github.com/ALaggyDev
      icon: github-square
      color: purple

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:title/
  - scope:
      path: ""
    values:
      layout: page

sass:
  style: compressed

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - rollup.config.js
  - "package*.json"
